# GitHub actions for Continuous Integration

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install g++-multilib scons
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install scons
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: pip install scons
      - name: Build
        run: build.bat
        shell: cmd
      - name: Test
        run: test.bat
        shell: cmd
